def email_message_with_safes():
    return '''\'02076\', \'000000\', \'DTAPPLU_ISSP2013Farm_1\', \r\n\r\n "DTAPINFR_NETWORKING_1", "DTAPAPPLU_ISHRFarm_1",\r\n\r\n
    "PAAPPL_CDCCDAM_1", "PAAPPL_GAMSORAINT_1"\r\n\r\n \r\n\r\n \r\n\r\nRegards\r\n\r\nPiotr Zawierucha\r\n\r\nDevOps 
    Trainee\r\n\r\nTech/Security/IAM/Privileged Account Security\r\n\r\n \r\n\r\n\r\n\r\nul. Konduktorska 35, 40-155\r\n\r\n \r\n'''


def email_message_with_approval():
    return '''Hi Team,\r\n\r\n \r\n\r\nPFB approval mail and share the activity and inventory reports of last 3 months for below Anvil PWV safes.\r\n\r\n \r\n\r\nRegards,\r\n\r\n \r\n\r\n\r\n\r\nSachin Kadam\r\n\r\nIT Engineer ION Platform\r\n\r\n \r\n\r\nING Wholesale Banking\r\n\r\nWB/FM&GT/Platform II/ION Platform\r\n\r\nMumbai,India\r\n\r\n
    \r\n\r\nT  +919869643072/ 7021997103\r\n\r\nLanline  +91 022 67797567/ 68\r\n\r\nNight Shift Standby  +91 7304964408\r\n\r\nE  Sachin.Kadam@ing.com <mailto:Sachin.Kadam@ing.com> \r\n\r\n \r\n\r\nFrom: Kapoor, T. (Tarun) <Tarun.Kapoor@ing.com> \r\nSent: donderdag 6 augustus 2020 21:41\r\nTo: Kadam, S. (Satchin) <Sachin.Kadam@ing.com>\r\nCc: Rai, A. (Ajeet) <Ajeet.Rai@ing.com>; DL-IND Anvil Support <DL-INDAnvilSupport@internal.ing.com>; Thuyl, D. van (Dustin) <Dustin.van.Thuyl@ing.com>; Selvaraj, V. (Vignesh) <Vignesh.Selvaraj@ing.com>; Gaur, A. (Arjun) <Arjun.Gaur@ing.com>\r\nSubject: Re: APPROVAL REQUIRED: Anvil PWV safes activity and inventory reports \r\n\r\n \r\n\r\nApproved.\r\n\r\n \r\n\r\nRegards,\r\n\r\nTarun Kapoor\r\n\r\n \r\n\r\n \r\n\r\nGet Outlook for iOS <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fo0ukef&data=02%7C01%7Cpassword.vault%40ing.com%7Cb30db0373ea542782e9008d83a247f51%7C587b6ea13db94fe1a9d785d4c64ce5cc%7C0%7C0%7C637323275731923995&sdata=eoXrSCmgHKHXaifDGKknFJEIYEyRwDIozdoqR6kpNDU%3D&reserved=0> \r\n\r\n________________________________\r\n\r\nFrom: Kadam, 
    S. (Satchin) <Sachin.Kadam@ing.com <mailto:Sachin.Kadam@ing.com> >\r\nSent: Thursday, August 6, 2020 5:35:08 PM\r\nTo: Kapoor, T. (Tarun) <Tarun.Kapoor@ing.com <mailto:Tarun.Kapoor@ing.com> >\r\nCc: Rai, A. (Ajeet) <Ajeet.Rai@ing.com <mailto:Ajeet.Rai@ing.com> >; DL-IND Anvil Support <DL-INDAnvilSupport@internal.ing.com <mailto:DL-INDAnvilSupport@internal.ing.com> >; Thuyl, D. van (Dustin) <Dustin.van.Thuyl@ing.com <mailto:Dustin.van.Thuyl@ing.com> >; Selvaraj, V. (Vignesh) <Vignesh.Selvaraj@ing.com <mailto:Vignesh.Selvaraj@ing.com> >; Gaur, A. (Arjun) <Arjun.Gaur@ing.com <mailto:Arjun.Gaur@ing.com> >\r\nSubject: APPROVAL REQUIRED: Anvil PWV safes activity and inventory reports \r\n\r\n \r\n\r\nHi Tarun,\r\n\r\n \r\n\r\nAs activity and inventory reports for below Anvil PWV safes is required for IT risk controls from PWV team. Can you please provide your approval to request the same ?\r\n\r\n \r\n\r\n08748DN_Anvil-DBAAS  and 08884CG_ANVIL-LDAP\r\n\r\nPWV_01996B_Anvil-Linux-NPA\r\n\r\nPWV_RootSafe_ 01923X_Anvil\r\n\r\nPWV 00950u_ANVIL-technical-NPAs\r\n\r\nPWV 01430_ANVIL-Oracle-NPAs\r\n\r\nPWV 01431_ANVIL-Application-NPAs\r\n\r\n02108W_Anvil-Windows\r\n\r\n04390B_Anvil-Ansible\r\n\r\n \r\n\r\nRegards,\r\n\r\n \r\n\r\n\r\n\r\nSachin Kadam\r\n\r\nIT Engineer ION Platform\r\n\r\n \r\n\r\nING Wholesale Banking\r\n\r\nWB/FM&GT/Platform II/ION Platform\r\n\r\nMumbai,India\r\n\r\n                                                                                                  \r\n\r\nT  +919869643072/ 7021997103\r\n\r\nLanline  +91 022 67797567/ 68\r\n\r\nNight Shift Standby  +91 7304964408\r\n\r\nE  Sachin.Kadam@ing.com <mailto:Sachin.Kadam@ing.com> \r\n\r\n \r\n'''
